apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: success-rate-check
  namespace: ran
spec:
  metrics:
    - name: http-success-rate
      interval: 30s
      count: 3
      successCondition: result > 95
      failureCondition: result < 95
      failureLimit: 1
      provider:
        web:
          url: http://drill3-rollout-practice.ran.svc.cluster.local/healthz
          method: GET
