apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: second-rollout
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 2
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: { duration: 60s }
        - analysis:
            templates:
              - templateName: success-rate-check
        - setWeight: 50
        - pause: { duration: 60s }
        - analysis:
            templates:
              - templateName: success-rate-check
        - setWeight: 100
  selector:
    matchLabels:
      {{- include "version1.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "version1.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-updated-again
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          ports:
            - containerPort: 80
