apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db-deployment
  labels:
    {{- include "mychart.argocd.db.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      {{- include "mychart.argocd.db.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mychart.argocd.db.labels" . | nindent 8 }}
    spec:
      containers:
        - name: mysql-container
          image: mysql:8.0
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-mysql-login-secret
                  value: password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: wp-mysql-login-secret
                  value: db_name
      restartPolicy: Always
