apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db-hl-service
spec:
  CluserIP: {{ .Values.db.ClusterIP }}
  selector:
    {{- include "mychart.argocd.db.labels" . | nindent 4 }}
  ports:
     - protocol: TCP
       port: {{ .Values.db.port }}
       targetPort: {{ .Values.db.port }}