apiVersion: v1
kind: Secret
metadata:
  name: wp-mysql-login-secret
data:
  MYSQL_DATABASE: bXlzcWwtZGF0YWJhc2U=
  MYSQL_ROOT_PASSWORD: d29yZHByZXNz
  WORDPRESS_DB_NAME: bXlzcWwtZGF0YWJhc2U=
  WORDPRESS_DB_PASSWORD: d29yZHByZXNz
  WORDPRESS_DB_USER: cm9vdA==

