apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Relase.Name }}-wp-deyployment
  labels:
    {{- include "mychart.argocd.labels" . | nindent 4 }}
spec:
  replicas: 3
  selector:
    matchLabels:
    {{- include "mychart.argocd.labels" . | nindent 6 }}
      
  template:
    metadata:
      labels:
        {{- include "mychart.argocd.labels" . | nindent 8 }}
    spec:
      containers:
      - name: wp-container
        image: wordpress
        env:
        - name: WORDPRESS_DB_USER
          value: root
        - name: WORDPRESS_DB_NAME
          value: mysql-database
        - name: WORDPRESS_DB_PASSWORD
          value: wordpress
        - name: WORDPRESS_DB_HOST
          value: mysql-port-service.default.svc.cluster.local # .local.... not necessarry when both pods are under the same namespace 
      restartPolicy: Always 