apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wp-deployment
  labels:
    {{- include "mychart.argocd.wp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.wp.replicaCount }}
  selector:
    matchLabels:
      {{- include "mychart.argocd.wp.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mychart.argocd.wp.labels" . | nindent 8 }}
    spec:
      containers:
        - name: wp-container
          image: wordpress
          env:
            - name: WORDPRESS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: wp-mysql-login-secret
                  value: WORDPRESS_DB_USER
            - name: WORDPRESS_DB_NAME
              valueFrom:
                secretKeyRef:
                  name: wp-mysql-login-secret
                  value: WORDPRESS_DB_NAME
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-mysql-login-secret
                  value: WORDPRESS_DB_PASSWORD
            - name: WORDPRESS_DB_HOST
              value: {{ .Release.Name }}-db-service.ran.svc.cluster.local # .local.... not necessary when both pods are under the same namespace
      restartPolicy: Always
