apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wp-service
spec:
  type: NodePort
  selector:
    {{- include "mychart.argocd.wp.labels" . | nindent 4 }}
  ports:
     - protocol: TCP
       port: {{ .Values.wp.port }}
       targetPort: {{ .Values.wp.port }}
       nodePort: 30080