apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
  labels: 
    {{- include "mychart.argocd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "mychart.argocd.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "mychart.argocd.labels" . | nindent 8 }} 
    spec:
      containers: 
        name: {{ .Values.image.repository }}-container
        image: {{ .Values.image.repository }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
      restartPolicy: Always
