apiVersion: v1
kind: Service
metadata:
  name: "{{ Release.Name }}-service"
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{- include "mychart.argocd.labels" . | nindent 4 }}
  ports:
     - protocol: TCP
       port: {{ .Values.service.port }}
       targetPort: 30080