apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drill3
  namespace: argocd
spec:
  project: default
  source:
    path: drill3/version1
    repoURL: 'https://github.com/Virgin28/ArgoCD'
    targetRevision: main
    helm:
      valueFiles:
        - /drill2/parameters-argo-cd/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ran
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true