apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: drill2
  namespace: argocd
spec:
  project: default
  source:
    path: drill2/parameters-argo-cd
    repoURL: 'https://github.com/Virgin28/ArgoCD'
    targetRevision: main
    helm:
      parameters:
        - name: wp.replicaCount
          value: "2"
        - name: wp.image
          value: "wordpress"
        - name: db.nodePort
          value: "NodePort"
        - name: db.image
          value: "mysql:8.0"
      valueFiles:
        - /drill2/parameters-argo-cd/values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: ran
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true